# This is a basic workflow to help you get started with Actions

name: Generic Lambda DEV CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.17.8
          # Whether to download only stable versions
          stable: true

      - name: Build go application
        run: |
          go version
          mkdir -p bin/${{ env.PACKAGE_NAME }}
          mkdir -p artifacts/${{ env.PACKAGE_NAME }}
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
          GOOS=linux GOARCH=amd64 go build -o ./bin/${{ env.PACKAGE_NAME }} ./cmd/${{ env.PACKAGE_NAME }}
          zip -j ./artifacts/${{ env.HANDLER_NAME }}.zip ./bin/${{ env.PACKAGE_NAME }}/${{ env.PACKAGE_NAME }}
      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: './artifacts'
          DEST_DIR: 'lambda'
          AWS_REGION: 'eu-central-1'
          AWS_S3_BUCKET: 'turtle-dev-config'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: default deploy
        uses: appleboy/lambda-action@v0.1.3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-central-1
          function_name: ${{ env.HANDLER_NAME }}
          zip_file: ./artifacts/${{ env.HANDLER_NAME }}.zip
