name: Auto approve
on: pull_request_target

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: Abildin/auto-approve-action@v1.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config: '.github/configs/auto-approve.json'
