on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    outputs:
      has_go_mod_changes : ${{ steps.changed-files-specific.outputs.only_changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files in the go.mod folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            go.mod/**
            go.sum

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23
          stable: true
      
      - name: Install dependencies   # Install all the dependencies
        run: |
          go version
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
          go get -u golang.org/x/lint/golint
      
      - name: Run build   # Run build of the application
        run: go build ./...
        
  auto-approve:
    name: Auto-approve PR with only go.mod changes
    runs-on: ubuntu-latest
    if: needs.build.outputs.has_go_mod_changes == 'true'
    needs: [build]
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v3
