on:
  workflow_call:
    inputs:
      HANDLER_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_S3_BUCKET:
        required: true
        type: string
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.23
          stable: true

      - name: Build go application
        run: |
          go version
          mkdir bin
          mkdir artifacts
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
          GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o ./bin/${{ inputs.PACKAGE_NAME }}/bootstrap ./cmd
          zip -j ./artifacts/${{ inputs.PACKAGE_NAME }}/bootstrap.zip ./bin/${{ inputs.PACKAGE_NAME }}/bootstrap
      - name: Push Zip to S3
        uses: jakejarvis/s3-sync-action@master
        env:
          SOURCE_DIR: ./artifacts/${{ inputs.PACKAGE_NAME }}
          DEST_DIR: lambda/${{ inputs.HANDLER_NAME }}
          AWS_REGION: ${{ inputs.AWS_REGION }}
          AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: default deploy
        uses: appleboy/lambda-action@v0.1.3
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ inputs.AWS_REGION }}
          function_name: ${{ inputs.HANDLER_NAME }}
          zip_file: ./artifacts/${{ inputs.PACKAGE_NAME }}/bootstrap.zip
