#This is a reusable workflow that builds lambda functions
on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
      HANDLER_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_S3_BUCKET:
        required: true
        type: string
      
        

jobs:
# This workflow contains a single job called "build"
 build:
  # The type of runner that the job will run on
  runs-on: ubuntu-latest

  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.21
        # Whether to download only stable versions
        stable: true

    - name: Build go application
      run: |
        go version
        mkdir -p bin/${{ inputs.PACKAGE_NAME }}
        mkdir -p artifacts/${{ inputs.PACKAGE_NAME }}
        git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
        GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o ./bin/${{ inputs.PACKAGE_NAME }}/bootstrap ./cmd/${{ inputs.PACKAGE_NAME }}
        zip -j ./artifacts/${{ inputs.PACKAGE_NAME }}/bootstrap.zip ./bin/${{ inputs.PACKAGE_NAME }}/bootstrap
    - name: Push Zip to S3
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: ./artifacts/${{ inputs.PACKAGE_NAME }}
        DEST_DIR: lambda/${{ inputs.HANDLER_NAME }}
        AWS_REGION: ${{ inputs.AWS_REGION }}
        AWS_S3_BUCKET: ${{ inputs.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: default deploy
      uses: appleboy/lambda-action@v0.1.3
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ inputs.AWS_REGION }}
        function_name: ${{ inputs.HANDLER_NAME }}
        zip_file: ./artifacts/${{ inputs.PACKAGE_NAME }}/bootstrap.zip
