on:
  workflow_call:
  
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
          
  test:
    runs-on: ubuntu-latest
    needs: [golangci-lint]
    steps:
      - uses: actions/checkout@v3

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.8
          stable: true

      # Install all the dependencies
      - name: Install dependencies
        run: |
          go version
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
          go get -u golang.org/x/lint/golint

      # Run build of the application
      - name: Run build
        run: go build ./...

      # Run tests on the code
      - name: Run tests
        run: go test ./...
