name: CI

on:
  workflow_call:

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      
      - name: Set up Git with access token
        run: |
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22  # Use the latest Go version
      
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.59.1
      
      - name: Run golangci-lint
        run: golangci-lint run --enable-all --exclude-use-default=false --timeout=10m

  test:
    runs-on: ubuntu-latest
    needs: [golangci-lint]
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22  # Ensure the Go version matches with the lint job
      
      - name: Set up Git with access token
        run: |
          git config --global url."https://${{ secrets.GIT_ACCESS_TOKEN }}:x-oauth-basic@github.com/go-turtle".insteadOf "https://github.com/go-turtle"
      
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint  # Optional, remove if not needed
      
      - name: Run build
        run: go build ./...
      
      - name: Run tests
        run: go test ./...
